CREATE DATABASE IF NOT EXISTS votingdb;
USE votingdb;

CREATE TABLE IF NOT EXISTS voters (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    aadhar_number VARCHAR(12) UNIQUE NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    constituency VARCHAR(50) NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vote_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voter_id VARCHAR(36) UNIQUE NOT NULL,
    candidate_id VARCHAR(50) NOT NULL,
    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SHOW TABLES;
